#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("ConferenceAppDroid.Resource", IsApplication=true)]

namespace ConferenceAppDroid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::SlidingMenuSharp.Resource.Attribute.behindOffset = global::ConferenceAppDroid.Resource.Attribute.behindOffset;
			global::SlidingMenuSharp.Resource.Attribute.behindScrollScale = global::ConferenceAppDroid.Resource.Attribute.behindScrollScale;
			global::SlidingMenuSharp.Resource.Attribute.behindWidth = global::ConferenceAppDroid.Resource.Attribute.behindWidth;
			global::SlidingMenuSharp.Resource.Attribute.fadeDegree = global::ConferenceAppDroid.Resource.Attribute.fadeDegree;
			global::SlidingMenuSharp.Resource.Attribute.fadeEnabled = global::ConferenceAppDroid.Resource.Attribute.fadeEnabled;
			global::SlidingMenuSharp.Resource.Attribute.mode = global::ConferenceAppDroid.Resource.Attribute.mode;
			global::SlidingMenuSharp.Resource.Attribute.selectorDrawable = global::ConferenceAppDroid.Resource.Attribute.selectorDrawable;
			global::SlidingMenuSharp.Resource.Attribute.selectorEnabled = global::ConferenceAppDroid.Resource.Attribute.selectorEnabled;
			global::SlidingMenuSharp.Resource.Attribute.shadowDrawable = global::ConferenceAppDroid.Resource.Attribute.shadowDrawable;
			global::SlidingMenuSharp.Resource.Attribute.shadowWidth = global::ConferenceAppDroid.Resource.Attribute.shadowWidth;
			global::SlidingMenuSharp.Resource.Attribute.touchModeAbove = global::ConferenceAppDroid.Resource.Attribute.touchModeAbove;
			global::SlidingMenuSharp.Resource.Attribute.touchModeBehind = global::ConferenceAppDroid.Resource.Attribute.touchModeBehind;
			global::SlidingMenuSharp.Resource.Attribute.viewAbove = global::ConferenceAppDroid.Resource.Attribute.viewAbove;
			global::SlidingMenuSharp.Resource.Attribute.viewBehind = global::ConferenceAppDroid.Resource.Attribute.viewBehind;
			global::SlidingMenuSharp.Resource.Id.fullscreen = global::ConferenceAppDroid.Resource.Id.fullscreen;
			global::SlidingMenuSharp.Resource.Id.left = global::ConferenceAppDroid.Resource.Id.left;
			global::SlidingMenuSharp.Resource.Id.margin = global::ConferenceAppDroid.Resource.Id.margin;
			global::SlidingMenuSharp.Resource.Id.right = global::ConferenceAppDroid.Resource.Id.right;
			global::SlidingMenuSharp.Resource.Id.selected_view = global::ConferenceAppDroid.Resource.Id.selected_view;
			global::SlidingMenuSharp.Resource.Id.slidingmenumain = global::ConferenceAppDroid.Resource.Id.slidingmenumain;
			global::SlidingMenuSharp.Resource.Layout.slidingmenumain = global::ConferenceAppDroid.Resource.Layout.slidingmenumain;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindOffset = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_behindOffset;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindScrollScale = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_behindScrollScale;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_behindWidth = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_behindWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeDegree = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_fadeDegree;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_fadeEnabled = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_fadeEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_mode = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_mode;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorDrawable = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_selectorDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_selectorEnabled = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_selectorEnabled;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowDrawable = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_shadowDrawable;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_shadowWidth = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_shadowWidth;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeAbove = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_touchModeAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_touchModeBehind = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_touchModeBehind;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewAbove = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_viewAbove;
			global::SlidingMenuSharp.Resource.Styleable.SlidingMenu_viewBehind = global::ConferenceAppDroid.Resource.Styleable.SlidingMenu_viewBehind;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.ApplicationName = global::ConferenceAppDroid.Resource.String.ApplicationName;
			global::SQLite.Net.Platform.XamarinAndroid.Resource.String.Hello = global::ConferenceAppDroid.Resource.String.Hello;
		}
		
		public partial class Animation
		{
			
			// aapt resource value: 0x7f040000
			public const int fadein = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int hold = 2130968577;
			
			// aapt resource value: 0x7f040002
			public const int ltr = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int none = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int pull_in_from_right = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int push_out_to_right = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int rotate = 2130968582;
			
			// aapt resource value: 0x7f040007
			public const int slide_down = 2130968583;
			
			// aapt resource value: 0x7f040008
			public const int slide_in_left = 2130968584;
			
			// aapt resource value: 0x7f040009
			public const int slide_in_right = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int slide_up = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int up_from_bottom = 2130968587;
			
			// aapt resource value: 0x7f04000c
			public const int up_from_bottom_rev = 2130968588;
			
			static Animation()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Animation()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010003
			public const int behindOffset = 2130771971;
			
			// aapt resource value: 0x7f010005
			public const int behindScrollScale = 2130771973;
			
			// aapt resource value: 0x7f010004
			public const int behindWidth = 2130771972;
			
			// aapt resource value: 0x7f01000b
			public const int fadeDegree = 2130771979;
			
			// aapt resource value: 0x7f01000a
			public const int fadeEnabled = 2130771978;
			
			// aapt resource value: 0x7f010000
			public const int mode = 2130771968;
			
			// aapt resource value: 0x7f01000d
			public const int selectorDrawable = 2130771981;
			
			// aapt resource value: 0x7f01000c
			public const int selectorEnabled = 2130771980;
			
			// aapt resource value: 0x7f010008
			public const int shadowDrawable = 2130771976;
			
			// aapt resource value: 0x7f010009
			public const int shadowWidth = 2130771977;
			
			// aapt resource value: 0x7f010006
			public const int touchModeAbove = 2130771974;
			
			// aapt resource value: 0x7f010007
			public const int touchModeBehind = 2130771975;
			
			// aapt resource value: 0x7f010001
			public const int viewAbove = 2130771969;
			
			// aapt resource value: 0x7f010002
			public const int viewBehind = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f07003a
			public const int app_colorPrimaryDark = 2131165242;
			
			// aapt resource value: 0x7f070002
			public const int black = 2131165186;
			
			// aapt resource value: 0x7f07000c
			public const int blue = 2131165196;
			
			// aapt resource value: 0x7f07000f
			public const int bronze = 2131165199;
			
			// aapt resource value: 0x7f07001f
			public const int builtio_file_select_item_color = 2131165215;
			
			// aapt resource value: 0x7f070029
			public const int create_note_save_text_pex = 2131165225;
			
			// aapt resource value: 0x7f070006
			public const int dark_grey = 2131165190;
			
			// aapt resource value: 0x7f070007
			public const int darker_grey = 2131165191;
			
			// aapt resource value: 0x7f070023
			public const int explore_list_background = 2131165219;
			
			// aapt resource value: 0x7f07000a
			public const int explore_middle_label = 2131165194;
			
			// aapt resource value: 0x7f070009
			public const int explore_top_label = 2131165193;
			
			// aapt resource value: 0x7f070035
			public const int explore_top_now_text_color = 2131165237;
			
			// aapt resource value: 0x7f070034
			public const int explore_top_now_title_color = 2131165236;
			
			// aapt resource value: 0x7f07000d
			public const int gold = 2131165197;
			
			// aapt resource value: 0x7f070005
			public const int grey = 2131165189;
			
			// aapt resource value: 0x7f070008
			public const int left_drawer_row_bg = 2131165192;
			
			// aapt resource value: 0x7f070038
			public const int left_menu_list_background = 2131165240;
			
			// aapt resource value: 0x7f070028
			public const int left_menu_name_text = 2131165224;
			
			// aapt resource value: 0x7f070027
			public const int left_menu_section_name_text = 2131165223;
			
			// aapt resource value: 0x7f070011
			public const int light_blue = 2131165201;
			
			// aapt resource value: 0x7f07001e
			public const int light_text = 2131165214;
			
			// aapt resource value: 0x7f070039
			public const int login_button_text = 2131165241;
			
			// aapt resource value: 0x7f070021
			public const int login_container_background = 2131165217;
			
			// aapt resource value: 0x7f070001
			public const int menu_default_color = 2131165185;
			
			// aapt resource value: 0x7f070000
			public const int menu_selected_color = 2131165184;
			
			// aapt resource value: 0x7f070010
			public const int pgrey = 2131165200;
			
			// aapt resource value: 0x7f070025
			public const int recommended_session_text = 2131165221;
			
			// aapt resource value: 0x7f070026
			public const int recommended_session_title_text = 2131165222;
			
			// aapt resource value: 0x7f070004
			public const int red = 2131165188;
			
			// aapt resource value: 0x7f07001c
			public const int right_menu_item_text_color = 2131165212;
			
			// aapt resource value: 0x7f07002a
			public const int search_bg = 2131165226;
			
			// aapt resource value: 0x7f07002e
			public const int search_cursor_color = 2131165230;
			
			// aapt resource value: 0x7f07002d
			public const int session_day_search_edit_text = 2131165229;
			
			// aapt resource value: 0x7f07002c
			public const int session_search_cancel_container_btn_bg_color = 2131165228;
			
			// aapt resource value: 0x7f07002b
			public const int session_search_cancel_container_btn_text_color = 2131165227;
			
			// aapt resource value: 0x7f07000e
			public const int silver = 2131165198;
			
			// aapt resource value: 0x7f070036
			public const int sync_info_text = 2131165238;
			
			// aapt resource value: 0x7f070037
			public const int sync_text_background = 2131165239;
			
			// aapt resource value: 0x7f07000b
			public const int tab_strib = 2131165195;
			
			// aapt resource value: 0x7f070033
			public const int text_color = 2131165235;
			
			// aapt resource value: 0x7f070017
			public const int text_desc_light_gray = 2131165207;
			
			// aapt resource value: 0x7f07001b
			public const int text_description = 2131165211;
			
			// aapt resource value: 0x7f070018
			public const int text_menu_datetime = 2131165208;
			
			// aapt resource value: 0x7f07001d
			public const int text_section_title = 2131165213;
			
			// aapt resource value: 0x7f070016
			public const int text_title_blue = 2131165206;
			
			// aapt resource value: 0x7f070019
			public const int theme_bottom_color = 2131165209;
			
			// aapt resource value: 0x7f070024
			public const int theme_tab_color = 2131165220;
			
			// aapt resource value: 0x7f07001a
			public const int theme_top_color = 2131165210;
			
			// aapt resource value: 0x7f070022
			public const int title_text_action_bar = 2131165218;
			
			// aapt resource value: 0x7f070014
			public const int tracks_filter_row_default_drawable = 2131165204;
			
			// aapt resource value: 0x7f070015
			public const int tracks_filter_row_pressed_drawable = 2131165205;
			
			// aapt resource value: 0x7f070012
			public const int tracks_filter_text_blue = 2131165202;
			
			// aapt resource value: 0x7f070013
			public const int tracks_filter_text_orange = 2131165203;
			
			// aapt resource value: 0x7f070020
			public const int transparent = 2131165216;
			
			// aapt resource value: 0x7f070003
			public const int white = 2131165187;
			
			// aapt resource value: 0x7f070031
			public const int widget_login_button_bg_color = 2131165233;
			
			// aapt resource value: 0x7f070032
			public const int widget_login_button_text_color = 2131165234;
			
			// aapt resource value: 0x7f07002f
			public const int widget_status_bar_color = 2131165231;
			
			// aapt resource value: 0x7f070030
			public const int widget_title_text_color = 2131165232;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f080003
			public const int activity_horizontal_margin = 2131230723;
			
			// aapt resource value: 0x7f080004
			public const int activity_vertical_margin = 2131230724;
			
			// aapt resource value: 0x7f080009
			public const int datetime_text_size = 2131230729;
			
			// aapt resource value: 0x7f08000a
			public const int desc_text_size = 2131230730;
			
			// aapt resource value: 0x7f080005
			public const int explore_track_corners = 2131230725;
			
			// aapt resource value: 0x7f080006
			public const int explore_track_corners_for_pex = 2131230726;
			
			// aapt resource value: 0x7f080001
			public const int list_padding = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int notification_text_size = 2131230728;
			
			// aapt resource value: 0x7f08000c
			public const int section_text_size = 2131230732;
			
			// aapt resource value: 0x7f080002
			public const int shadow_width = 2131230722;
			
			// aapt resource value: 0x7f080000
			public const int slidingmenu_offset = 2131230720;
			
			// aapt resource value: 0x7f08000b
			public const int terms_and_condition_text_size_for_pex = 2131230731;
			
			// aapt resource value: 0x7f080007
			public const int title_text_size = 2131230727;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int arrow = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int background_left_tab = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int background_left_tab_selected = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int background_rounded_corner_blue = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int background_top_line = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int bg_app = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int bg_blue_cursor = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int bg_button = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int bg_checkbox_selection = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int bg_image_detailpage = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int bg_menu_row = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int bg_repeat_blueish_white = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int bg_repeat_leftmenu_normal = 2130837516;
			
			// aapt resource value: 0x7f02009d
			public const int bg_repeat_session = 2130837661;
			
			// aapt resource value: 0x7f02000d
			public const int bg_selector_login_username_password = 2130837517;
			
			// aapt resource value: 0x7f02009e
			public const int bg_settings_menu = 2130837662;
			
			// aapt resource value: 0x7f02000e
			public const int bg_shape_left_blue_tracks_disabled = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int bg_shape_left_blue_tracks_selected = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int bg_shape_left_blue_tracks_unselected = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int bg_shape_right_blue_tracks_disabled = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int bg_shape_right_blue_tracks_selected = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int bg_shape_right_blue_tracks_unselected = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int bg_splash = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int bg_splash_01 = 2130837525;
			
			// aapt resource value: 0x7f02009c
			public const int bg_white = 2130837660;
			
			// aapt resource value: 0x7f020016
			public const int bg_white_cursor = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int check = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int circle = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int close_icon_selector = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int dropshadow = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int dropshadow_topbottom = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int favorite2 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int ic_1st = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int ic_2cd = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int ic_3rd = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int ic_action_navigation_arrow_back = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int ic_action_navigation_back = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int ic_add_interest = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int ic_add_interest_selected = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ic_add_schedule_row = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ic_add_session = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ic_all_feed_reply = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ic_all_feed_retweet = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ic_back_arrow = 2130837544;
			
			// aapt resource value: 0x7f020029
			public const int ic_bkcamera_blue = 2130837545;
			
			// aapt resource value: 0x7f02002a
			public const int ic_bkcamera_gray = 2130837546;
			
			// aapt resource value: 0x7f02002b
			public const int ic_blue_arrow_back = 2130837547;
			
			// aapt resource value: 0x7f02002c
			public const int ic_blue_arrow_frwd = 2130837548;
			
			// aapt resource value: 0x7f02002d
			public const int ic_bottom = 2130837549;
			
			// aapt resource value: 0x7f02002e
			public const int ic_camera_orange_2x = 2130837550;
			
			// aapt resource value: 0x7f02002f
			public const int ic_camera_selected = 2130837551;
			
			// aapt resource value: 0x7f020030
			public const int ic_checkbox = 2130837552;
			
			// aapt resource value: 0x7f020031
			public const int ic_checkbox_selected = 2130837553;
			
			// aapt resource value: 0x7f020032
			public const int ic_close_login = 2130837554;
			
			// aapt resource value: 0x7f020033
			public const int ic_close_preview = 2130837555;
			
			// aapt resource value: 0x7f020034
			public const int ic_content_discard = 2130837556;
			
			// aapt resource value: 0x7f020035
			public const int ic_content_discard_selected = 2130837557;
			
			// aapt resource value: 0x7f020036
			public const int ic_default_pic = 2130837558;
			
			// aapt resource value: 0x7f020037
			public const int ic_delete_recipient = 2130837559;
			
			// aapt resource value: 0x7f020038
			public const int ic_external_link_icon = 2130837560;
			
			// aapt resource value: 0x7f020039
			public const int ic_facebook = 2130837561;
			
			// aapt resource value: 0x7f02003a
			public const int ic_follow_text = 2130837562;
			
			// aapt resource value: 0x7f02003b
			public const int ic_follow_text_gray = 2130837563;
			
			// aapt resource value: 0x7f02003c
			public const int ic_gray_arrow_back = 2130837564;
			
			// aapt resource value: 0x7f02003d
			public const int ic_gray_arrow_frwd = 2130837565;
			
			// aapt resource value: 0x7f02003e
			public const int ic_help = 2130837566;
			
			// aapt resource value: 0x7f02003f
			public const int ic_instagram = 2130837567;
			
			// aapt resource value: 0x7f020040
			public const int ic_instagram_comment = 2130837568;
			
			// aapt resource value: 0x7f020041
			public const int ic_instagram_love = 2130837569;
			
			// aapt resource value: 0x7f020042
			public const int ic_launcher = 2130837570;
			
			// aapt resource value: 0x7f020043
			public const int ic_loading_splash = 2130837571;
			
			// aapt resource value: 0x7f020044
			public const int ic_location_place = 2130837572;
			
			// aapt resource value: 0x7f020045
			public const int ic_new_camera_menu = 2130837573;
			
			// aapt resource value: 0x7f020046
			public const int ic_new_compose_normal = 2130837574;
			
			// aapt resource value: 0x7f020047
			public const int ic_new_compose_selected = 2130837575;
			
			// aapt resource value: 0x7f020048
			public const int ic_new_note_menu = 2130837576;
			
			// aapt resource value: 0x7f020049
			public const int ic_new_note_menu_selected = 2130837577;
			
			// aapt resource value: 0x7f02004a
			public const int ic_new_qr_menu = 2130837578;
			
			// aapt resource value: 0x7f02004b
			public const int ic_notification = 2130837579;
			
			// aapt resource value: 0x7f02004c
			public const int ic_notification_selected = 2130837580;
			
			// aapt resource value: 0x7f02004d
			public const int ic_password = 2130837581;
			
			// aapt resource value: 0x7f02004e
			public const int ic_password_selected = 2130837582;
			
			// aapt resource value: 0x7f02004f
			public const int ic_profile = 2130837583;
			
			// aapt resource value: 0x7f020050
			public const int ic_profile_pic_normal = 2130837584;
			
			// aapt resource value: 0x7f020051
			public const int ic_pulltorefresh_arrow = 2130837585;
			
			// aapt resource value: 0x7f020052
			public const int ic_scanner_selected = 2130837586;
			
			// aapt resource value: 0x7f020053
			public const int ic_schedule_row = 2130837587;
			
			// aapt resource value: 0x7f020054
			public const int ic_screen_close = 2130837588;
			
			// aapt resource value: 0x7f020055
			public const int ic_screen_close_hover = 2130837589;
			
			// aapt resource value: 0x7f020056
			public const int ic_selfie = 2130837590;
			
			// aapt resource value: 0x7f020057
			public const int ic_selfie_gray = 2130837591;
			
			// aapt resource value: 0x7f020058
			public const int ic_setting = 2130837592;
			
			// aapt resource value: 0x7f020059
			public const int ic_tab_achievements_normal = 2130837593;
			
			// aapt resource value: 0x7f02005a
			public const int ic_tab_achievements_selected = 2130837594;
			
			// aapt resource value: 0x7f02005b
			public const int ic_tab_activity_normal = 2130837595;
			
			// aapt resource value: 0x7f02005c
			public const int ic_tab_activity_selected = 2130837596;
			
			// aapt resource value: 0x7f02005d
			public const int ic_tab_foodndrink_normal = 2130837597;
			
			// aapt resource value: 0x7f02005e
			public const int ic_tab_foodndrink_selected = 2130837598;
			
			// aapt resource value: 0x7f02005f
			public const int ic_tab_schedule_normal = 2130837599;
			
			// aapt resource value: 0x7f020060
			public const int ic_tab_schedule_selected = 2130837600;
			
			// aapt resource value: 0x7f020061
			public const int ic_tab_speakers_normal = 2130837601;
			
			// aapt resource value: 0x7f020062
			public const int ic_tab_speakers_selected = 2130837602;
			
			// aapt resource value: 0x7f020063
			public const int ic_tab_transportation_normal = 2130837603;
			
			// aapt resource value: 0x7f020064
			public const int ic_tab_transportation_selected = 2130837604;
			
			// aapt resource value: 0x7f020065
			public const int ic_tag_close2x = 2130837605;
			
			// aapt resource value: 0x7f020066
			public const int ic_tags_icon_blue = 2130837606;
			
			// aapt resource value: 0x7f020067
			public const int ic_tags_icon_gray = 2130837607;
			
			// aapt resource value: 0x7f020068
			public const int ic_twitter = 2130837608;
			
			// aapt resource value: 0x7f020069
			public const int ic_unknown = 2130837609;
			
			// aapt resource value: 0x7f02006a
			public const int ic_up_arrow = 2130837610;
			
			// aapt resource value: 0x7f02006b
			public const int ic_video_play = 2130837611;
			
			// aapt resource value: 0x7f02006c
			public const int ic_vmworldapp_logo = 2130837612;
			
			// aapt resource value: 0x7f02006d
			public const int Icon = 2130837613;
			
			// aapt resource value: 0x7f02006e
			public const int indicator = 2130837614;
			
			// aapt resource value: 0x7f02006f
			public const int is_open_left_menu = 2130837615;
			
			// aapt resource value: 0x7f020070
			public const int layerlist_bottom_grey_line = 2130837616;
			
			// aapt resource value: 0x7f020071
			public const int layerlist_bottom_session_new_design = 2130837617;
			
			// aapt resource value: 0x7f020072
			public const int layerlist_explore_middle_label = 2130837618;
			
			// aapt resource value: 0x7f020073
			public const int layerlist_section_bg_new_design = 2130837619;
			
			// aapt resource value: 0x7f020074
			public const int layout1 = 2130837620;
			
			// aapt resource value: 0x7f020075
			public const int main_bg = 2130837621;
			
			// aapt resource value: 0x7f020076
			public const int more = 2130837622;
			
			// aapt resource value: 0x7f020077
			public const int new_indicator = 2130837623;
			
			// aapt resource value: 0x7f020078
			public const int rounded_bg_tracks_view = 2130837624;
			
			// aapt resource value: 0x7f020079
			public const int rounded_corner_pex_blue = 2130837625;
			
			// aapt resource value: 0x7f02007a
			public const int search_large = 2130837626;
			
			// aapt resource value: 0x7f02007b
			public const int selector_camera = 2130837627;
			
			// aapt resource value: 0x7f02007c
			public const int selector_create_note = 2130837628;
			
			// aapt resource value: 0x7f02007d
			public const int selector_delete_note = 2130837629;
			
			// aapt resource value: 0x7f02007e
			public const int selector_left_blue_tracks_session_detail = 2130837630;
			
			// aapt resource value: 0x7f02007f
			public const int selector_left_tab = 2130837631;
			
			// aapt resource value: 0x7f020080
			public const int selector_new_tweet = 2130837632;
			
			// aapt resource value: 0x7f020081
			public const int selector_password = 2130837633;
			
			// aapt resource value: 0x7f020082
			public const int selector_profile = 2130837634;
			
			// aapt resource value: 0x7f020083
			public const int selector_right_blue_tracks_session_detail = 2130837635;
			
			// aapt resource value: 0x7f020084
			public const int selector_selfie = 2130837636;
			
			// aapt resource value: 0x7f020085
			public const int selector_session_row = 2130837637;
			
			// aapt resource value: 0x7f020086
			public const int selector_tab_foodndrink = 2130837638;
			
			// aapt resource value: 0x7f020087
			public const int selector_tab_schedule = 2130837639;
			
			// aapt resource value: 0x7f020088
			public const int selector_tab_speakers = 2130837640;
			
			// aapt resource value: 0x7f020089
			public const int selector_tab_transportation = 2130837641;
			
			// aapt resource value: 0x7f02008a
			public const int selector_tags_imageview = 2130837642;
			
			// aapt resource value: 0x7f02008b
			public const int selector_tracks_row = 2130837643;
			
			// aapt resource value: 0x7f02008c
			public const int selector_twitter = 2130837644;
			
			// aapt resource value: 0x7f02009b
			public const int session_track_color_drawable = 2130837659;
			
			// aapt resource value: 0x7f02008d
			public const int shadow = 2130837645;
			
			// aapt resource value: 0x7f02008e
			public const int shadowright = 2130837646;
			
			// aapt resource value: 0x7f02008f
			public const int shape_add_note = 2130837647;
			
			// aapt resource value: 0x7f020090
			public const int shape_login_screen = 2130837648;
			
			// aapt resource value: 0x7f020091
			public const int shape_login_selected_textview = 2130837649;
			
			// aapt resource value: 0x7f020092
			public const int shape_login_textview = 2130837650;
			
			// aapt resource value: 0x7f020093
			public const int shape_rectangle = 2130837651;
			
			// aapt resource value: 0x7f020094
			public const int shape_rectangle_sponsors_by_contribution = 2130837652;
			
			// aapt resource value: 0x7f020095
			public const int splash_loading_drawable = 2130837653;
			
			// aapt resource value: 0x7f020096
			public const int switcher_off = 2130837654;
			
			// aapt resource value: 0x7f020097
			public const int switcher_toggle_on = 2130837655;
			
			// aapt resource value: 0x7f020098
			public const int twitter_reply_dialog_drawable = 2130837656;
			
			// aapt resource value: 0x7f020099
			public const int vmworld_logo_black = 2130837657;
			
			// aapt resource value: 0x7f02009a
			public const int vmworld_logo_white = 2130837658;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f06004e
			public const int FoodNDrinkListView = 2131099726;
			
			// aapt resource value: 0x7f0600c4
			public const int FoodNDrinks_tab_btn_container = 2131099844;
			
			// aapt resource value: 0x7f0600c5
			public const int FoodNDrinks_tab_icon = 2131099845;
			
			// aapt resource value: 0x7f0600d9
			public const int HorizontalScrollView01 = 2131099865;
			
			// aapt resource value: 0x7f060178
			public const int Interest_NoData_TextView = 2131100024;
			
			// aapt resource value: 0x7f0600c2
			public const int Transportation_tab_btn_container = 2131099842;
			
			// aapt resource value: 0x7f0600c3
			public const int Transportation_tab_icon = 2131099843;
			
			// aapt resource value: 0x7f0600f4
			public const int actionBarTitleContainer = 2131099892;
			
			// aapt resource value: 0x7f0600fd
			public const int action_bar_buttons = 2131099901;
			
			// aapt resource value: 0x7f060100
			public const int action_bar_help_icon_iv = 2131099904;
			
			// aapt resource value: 0x7f0600ff
			public const int action_bar_search_icon_iv = 2131099903;
			
			// aapt resource value: 0x7f06019d
			public const int action_container = 2131100061;
			
			// aapt resource value: 0x7f060136
			public const int addRemoveSession = 2131099958;
			
			// aapt resource value: 0x7f060137
			public const int addToMyScheduleContainer = 2131099959;
			
			// aapt resource value: 0x7f060164
			public const int add_note_container = 2131100004;
			
			// aapt resource value: 0x7f060165
			public const int add_note_icon = 2131100005;
			
			// aapt resource value: 0x7f060166
			public const int add_note_label = 2131100006;
			
			// aapt resource value: 0x7f06015d
			public const int add_note_realative_layout = 2131099997;
			
			// aapt resource value: 0x7f060139
			public const int addedToScheduleContainer = 2131099961;
			
			// aapt resource value: 0x7f060027
			public const int addressTextView = 2131099687;
			
			// aapt resource value: 0x7f060112
			public const int all_feed_fb_comments_container = 2131099922;
			
			// aapt resource value: 0x7f060110
			public const int all_feed_fb_likes_container = 2131099920;
			
			// aapt resource value: 0x7f06017d
			public const int attachmentButton = 2131100029;
			
			// aapt resource value: 0x7f0600fa
			public const int back_btn = 2131099898;
			
			// aapt resource value: 0x7f060030
			public const int bottomActionContainer = 2131099696;
			
			// aapt resource value: 0x7f06001a
			public const int bottomContainer = 2131099674;
			
			// aapt resource value: 0x7f06002e
			public const int bottomDetailContainer = 2131099694;
			
			// aapt resource value: 0x7f0600f9
			public const int bottomImageView = 2131099897;
			
			// aapt resource value: 0x7f060075
			public const int btn1 = 2131099765;
			
			// aapt resource value: 0x7f060076
			public const int btn2 = 2131099766;
			
			// aapt resource value: 0x7f060077
			public const int btn3 = 2131099767;
			
			// aapt resource value: 0x7f060074
			public const int btnLogin = 2131099764;
			
			// aapt resource value: 0x7f060072
			public const int btnNext = 2131099762;
			
			// aapt resource value: 0x7f060071
			public const int btnPrevious = 2131099761;
			
			// aapt resource value: 0x7f060119
			public const int cameraTextView = 2131099929;
			
			// aapt resource value: 0x7f060160
			public const int cancelImageView = 2131100000;
			
			// aapt resource value: 0x7f0601a0
			public const int cancel_drop_down = 2131100064;
			
			// aapt resource value: 0x7f06001d
			public const int clear_password_imageview = 2131099677;
			
			// aapt resource value: 0x7f06001b
			public const int clear_username_imageview = 2131099675;
			
			// aapt resource value: 0x7f06014a
			public const int competency_textview_id = 2131099978;
			
			// aapt resource value: 0x7f06014c
			public const int competency_textview_value = 2131099980;
			
			// aapt resource value: 0x7f060043
			public const int container = 2131099715;
			
			// aapt resource value: 0x7f060085
			public const int content_frame = 2131099781;
			
			// aapt resource value: 0x7f060040
			public const int copy_rights_TextView = 2131099712;
			
			// aapt resource value: 0x7f060032
			public const int createNewNoteImageView = 2131099698;
			
			// aapt resource value: 0x7f06007f
			public const int dateTextView = 2131099775;
			
			// aapt resource value: 0x7f060181
			public const int date_of_session_tv = 2131100033;
			
			// aapt resource value: 0x7f060180
			public const int day_of_session_tv = 2131100032;
			
			// aapt resource value: 0x7f060031
			public const int deleteImageView = 2131099697;
			
			// aapt resource value: 0x7f060102
			public const int deleteTextView = 2131099906;
			
			// aapt resource value: 0x7f060048
			public const int description = 2131099720;
			
			// aapt resource value: 0x7f060028
			public const int descriptionTextView = 2131099688;
			
			// aapt resource value: 0x7f060101
			public const int doneTextView = 2131099905;
			
			// aapt resource value: 0x7f06019e
			public const int drop_down_listview = 2131100062;
			
			// aapt resource value: 0x7f06011d
			public const int exploreIntro_container = 2131099933;
			
			// aapt resource value: 0x7f06011e
			public const int exploreIntro_imageview_coverImage = 2131099934;
			
			// aapt resource value: 0x7f06011f
			public const int exploreIntro_textview_intro = 2131099935;
			
			// aapt resource value: 0x7f060125
			public const int exploreNextUpHorizontalScrollView = 2131099941;
			
			// aapt resource value: 0x7f060122
			public const int exploreNowHorizontalScrollView = 2131099938;
			
			// aapt resource value: 0x7f060124
			public const int explore_next_up_label = 2131099940;
			
			// aapt resource value: 0x7f060121
			public const int explore_now_label = 2131099937;
			
			// aapt resource value: 0x7f0600a2
			public const int explore_top_now_session_container = 2131099810;
			
			// aapt resource value: 0x7f0600a4
			public const int explore_top_now_session_room_tv = 2131099812;
			
			// aapt resource value: 0x7f0600a5
			public const int explore_top_now_session_time_tv = 2131099813;
			
			// aapt resource value: 0x7f0600a3
			public const int explore_top_now_session_title_tv = 2131099811;
			
			// aapt resource value: 0x7f06004c
			public const int faq_textview_title = 2131099724;
			
			// aapt resource value: 0x7f0600de
			public const int filter_sub_tracks_title_tv = 2131099870;
			
			// aapt resource value: 0x7f0600dc
			public const int filter_tracks_title_tv = 2131099868;
			
			// aapt resource value: 0x7f06004d
			public const int foodNDrinkGroup = 2131099725;
			
			// aapt resource value: 0x7f060022
			public const int forgetPasswordTextView = 2131099682;
			
			// aapt resource value: 0x7f060021
			public const int forgetUsernameTextView = 2131099681;
			
			// aapt resource value: 0x7f0600c8
			public const int frame_layout = 2131099848;
			
			// aapt resource value: 0x7f060003
			public const int fullscreen = 2131099651;
			
			// aapt resource value: 0x7f06006e
			public const int gridView = 2131099758;
			
			// aapt resource value: 0x7f060006
			public const int handsOnAbbreviationTextView = 2131099654;
			
			// aapt resource value: 0x7f060007
			public const int handsOnDescriptionTextView = 2131099655;
			
			// aapt resource value: 0x7f06011b
			public const int handsOnLabsListView = 2131099931;
			
			// aapt resource value: 0x7f060005
			public const int handsOnTitleTextView = 2131099653;
			
			// aapt resource value: 0x7f060192
			public const int headerTextView = 2131100050;
			
			// aapt resource value: 0x7f06000d
			public const int holDetail_textview_capacity_label = 2131099661;
			
			// aapt resource value: 0x7f06000e
			public const int holDetail_textview_capacity_value = 2131099662;
			
			// aapt resource value: 0x7f06000b
			public const int holDetail_textview_duration_label = 2131099659;
			
			// aapt resource value: 0x7f06000c
			public const int holDetail_textview_duration_value = 2131099660;
			
			// aapt resource value: 0x7f060009
			public const int holDetail_textview_id = 2131099657;
			
			// aapt resource value: 0x7f06000a
			public const int holDetail_textview_value = 2131099658;
			
			// aapt resource value: 0x7f06000f
			public const int holDetail_twitter_hash_tag_id = 2131099663;
			
			// aapt resource value: 0x7f060010
			public const int holDetail_twitter_hash_tag_value = 2131099664;
			
			// aapt resource value: 0x7f060012
			public const int holDetails_speakerSectionTextView = 2131099666;
			
			// aapt resource value: 0x7f060008
			public const int holInfoContainer = 2131099656;
			
			// aapt resource value: 0x7f060011
			public const int holSpeakerContainer = 2131099665;
			
			// aapt resource value: 0x7f060013
			public const int hol_speaker_list_container = 2131099667;
			
			// aapt resource value: 0x7f06005c
			public const int horizontalLine = 2131099740;
			
			// aapt resource value: 0x7f060065
			public const int horizontalLine_2 = 2131099749;
			
			// aapt resource value: 0x7f0600c9
			public const int imageHorizontalScrollView = 2131099849;
			
			// aapt resource value: 0x7f06015f
			public const int imageView = 2131099999;
			
			// aapt resource value: 0x7f06004f
			public const int importantLinksList = 2131099727;
			
			// aapt resource value: 0x7f0600a8
			public const int important_link_sectionTitle = 2131099816;
			
			// aapt resource value: 0x7f0600a7
			public const int important_section = 2131099815;
			
			// aapt resource value: 0x7f060129
			public const int leaderBoardConianier = 2131099945;
			
			// aapt resource value: 0x7f060126
			public const int leaderBoardMainConianier = 2131099942;
			
			// aapt resource value: 0x7f060127
			public const int leaderBoardlabelTextView = 2131099943;
			
			// aapt resource value: 0x7f060128
			public const int leader_board_help_icon = 2131099944;
			
			// aapt resource value: 0x7f060001
			public const int left = 2131099649;
			
			// aapt resource value: 0x7f06002f
			public const int leftArrowImageView = 2131099695;
			
			// aapt resource value: 0x7f0600f5
			public const int leftMenuContainer = 2131099893;
			
			// aapt resource value: 0x7f0600b6
			public const int left_drawer_info_tv = 2131099830;
			
			// aapt resource value: 0x7f06016a
			public const int left_drawer_list = 2131100010;
			
			// aapt resource value: 0x7f0600af
			public const int left_drawer_row_parent = 2131099823;
			
			// aapt resource value: 0x7f0600b4
			public const int left_drawer_row_tv = 2131099828;
			
			// aapt resource value: 0x7f0600b5
			public const int left_drawer_value_tv = 2131099829;
			
			// aapt resource value: 0x7f0600f6
			public const int left_menu_btn = 2131099894;
			
			// aapt resource value: 0x7f0600b2
			public const int left_menu_icon = 2131099826;
			
			// aapt resource value: 0x7f0600b3
			public const int left_menu_right_arrow = 2131099827;
			
			// aapt resource value: 0x7f0600f7
			public const int left_menu_textview = 2131099895;
			
			// aapt resource value: 0x7f0600f8
			public const int left_new_notification_imageview = 2131099896;
			
			// aapt resource value: 0x7f060078
			public const int list = 2131099768;
			
			// aapt resource value: 0x7f0600b0
			public const int listSeperatorTextView = 2131099824;
			
			// aapt resource value: 0x7f060079
			public const int list_header_title = 2131099769;
			
			// aapt resource value: 0x7f060019
			public const int loadingContainer = 2131099673;
			
			// aapt resource value: 0x7f06003b
			public const int loadingContainerForPex = 2131099707;
			
			// aapt resource value: 0x7f060084
			public const int loadingText = 2131099780;
			
			// aapt resource value: 0x7f06016f
			public const int loading_list_tv = 2131100015;
			
			// aapt resource value: 0x7f060131
			public const int locationAndTimeTextView = 2131099953;
			
			// aapt resource value: 0x7f060130
			public const int locationContainer = 2131099952;
			
			// aapt resource value: 0x7f060020
			public const int loginButton = 2131099680;
			
			// aapt resource value: 0x7f060018
			public const int login_screen_logo = 2131099672;
			
			// aapt resource value: 0x7f060095
			public const int lstFaq = 2131099797;
			
			// aapt resource value: 0x7f060179
			public const int lstInterest = 2131100025;
			
			// aapt resource value: 0x7f06004a
			public const int lstNews = 2131099722;
			
			// aapt resource value: 0x7f0600f3
			public const int lstVenue = 2131099891;
			
			// aapt resource value: 0x7f060049
			public const int lvTweets = 2131099721;
			
			// aapt resource value: 0x7f060016
			public const int mainRelativeLayout = 2131099670;
			
			// aapt resource value: 0x7f0600aa
			public const int maincontainer = 2131099818;
			
			// aapt resource value: 0x7f060004
			public const int margin = 2131099652;
			
			// aapt resource value: 0x7f060086
			public const int menu_frame = 2131099782;
			
			// aapt resource value: 0x7f0600b1
			public const int menu_item_container = 2131099825;
			
			// aapt resource value: 0x7f06016e
			public const int messageTextViewFromLoading = 2131100014;
			
			// aapt resource value: 0x7f060025
			public const int mosconeImageContainer = 2131099685;
			
			// aapt resource value: 0x7f060026
			public const int mosconeImageView = 2131099686;
			
			// aapt resource value: 0x7f0600f0
			public const int moscone_row_arrow = 2131099888;
			
			// aapt resource value: 0x7f0600f2
			public const int moscone_row_desc = 2131099890;
			
			// aapt resource value: 0x7f0600f1
			public const int moscone_row_title = 2131099889;
			
			// aapt resource value: 0x7f060055
			public const int myNotesListView = 2131099733;
			
			// aapt resource value: 0x7f0600c7
			public const int my_schedule_fragment_container = 2131099847;
			
			// aapt resource value: 0x7f06015c
			public const int nameTextView = 2131099996;
			
			// aapt resource value: 0x7f060050
			public const int newNotesButton = 2131099728;
			
			// aapt resource value: 0x7f06011a
			public const int newTweetTextView = 2131099930;
			
			// aapt resource value: 0x7f06008d
			public const int newsActionContainer = 2131099789;
			
			// aapt resource value: 0x7f060090
			public const int newsDetail_coverImage = 2131099792;
			
			// aapt resource value: 0x7f06008f
			public const int newsDetail_coverImage_container = 2131099791;
			
			// aapt resource value: 0x7f060093
			public const int newsDetail_textview_descr = 2131099795;
			
			// aapt resource value: 0x7f060092
			public const int newsDetail_textview_publishedDate = 2131099794;
			
			// aapt resource value: 0x7f060094
			public const int newsDetail_textview_readMore = 2131099796;
			
			// aapt resource value: 0x7f060091
			public const int newsDetail_textview_title = 2131099793;
			
			// aapt resource value: 0x7f06008c
			public const int news_textview_descr = 2131099788;
			
			// aapt resource value: 0x7f06008b
			public const int news_textview_publishedDate = 2131099787;
			
			// aapt resource value: 0x7f06008a
			public const int news_textview_title = 2131099786;
			
			// aapt resource value: 0x7f060123
			public const int nextContainer = 2131099939;
			
			// aapt resource value: 0x7f0600cf
			public const int notesContainer = 2131099855;
			
			// aapt resource value: 0x7f060081
			public const int notesContentTextView = 2131099777;
			
			// aapt resource value: 0x7f0600d2
			public const int notesDetail_editText = 2131099858;
			
			// aapt resource value: 0x7f060051
			public const int notesGroup = 2131099729;
			
			// aapt resource value: 0x7f060080
			public const int notesTitleTextView = 2131099776;
			
			// aapt resource value: 0x7f0600d0
			public const int notesTitle_editText_title = 2131099856;
			
			// aapt resource value: 0x7f06015e
			public const int notes_progress_bar = 2131099998;
			
			// aapt resource value: 0x7f0600d1
			public const int notestime_textView = 2131099857;
			
			// aapt resource value: 0x7f060175
			public const int notificationCountTextView = 2131100021;
			
			// aapt resource value: 0x7f060174
			public const int notification_icon = 2131100020;
			
			// aapt resource value: 0x7f060173
			public const int notification_received_imageView = 2131100019;
			
			// aapt resource value: 0x7f060120
			public const int nowContainer = 2131099936;
			
			// aapt resource value: 0x7f0600a1
			public const int now_next_parent_container = 2131099809;
			
			// aapt resource value: 0x7f0600a6
			public const int now_next_track_color = 2131099814;
			
			// aapt resource value: 0x7f060052
			public const int optionDate = 2131099730;
			
			// aapt resource value: 0x7f060054
			public const int optionTag = 2131099732;
			
			// aapt resource value: 0x7f060053
			public const int optionTitle = 2131099731;
			
			// aapt resource value: 0x7f0600a9
			public const int others_dummy_view1 = 2131099817;
			
			// aapt resource value: 0x7f0600ae
			public const int others_dummy_view2 = 2131099822;
			
			// aapt resource value: 0x7f060038
			public const int pager = 2131099704;
			
			// aapt resource value: 0x7f06001e
			public const int passwordEditText = 2131099678;
			
			// aapt resource value: 0x7f06012e
			public const int popularSessionlabelTextView = 2131099950;
			
			// aapt resource value: 0x7f060015
			public const int previewImageView = 2131099669;
			
			// aapt resource value: 0x7f060046
			public const int progress = 2131099718;
			
			// aapt resource value: 0x7f060014
			public const int progressBar = 2131099668;
			
			// aapt resource value: 0x7f06003d
			public const int progressBarForPex = 2131099709;
			
			// aapt resource value: 0x7f060083
			public const int progressbar = 2131099779;
			
			// aapt resource value: 0x7f060044
			public const int progrss = 2131099716;
			
			// aapt resource value: 0x7f060096
			public const int pull_to_refresh_header = 2131099798;
			
			// aapt resource value: 0x7f060098
			public const int pull_to_refresh_image = 2131099800;
			
			// aapt resource value: 0x7f060097
			public const int pull_to_refresh_progress = 2131099799;
			
			// aapt resource value: 0x7f060099
			public const int pull_to_refresh_text = 2131099801;
			
			// aapt resource value: 0x7f06009a
			public const int pull_to_refresh_updated_at = 2131099802;
			
			// aapt resource value: 0x7f060082
			public const int relativeLayout = 2131099778;
			
			// aapt resource value: 0x7f0601a1
			public const int remove_filter = 2131100065;
			
			// aapt resource value: 0x7f06017e
			public const int res = 2131100030;
			
			// aapt resource value: 0x7f060002
			public const int right = 2131099650;
			
			// aapt resource value: 0x7f060037
			public const int rightArrowImageView = 2131099703;
			
			// aapt resource value: 0x7f0600fb
			public const int right_menu_btn = 2131099899;
			
			// aapt resource value: 0x7f0600fc
			public const int right_new_notification_imageview = 2131099900;
			
			// aapt resource value: 0x7f06004b
			public const int row_faq_arrow = 2131099723;
			
			// aapt resource value: 0x7f06007d
			public const int row_handsonlab_arrow = 2131099773;
			
			// aapt resource value: 0x7f06007c
			public const int row_handsonlab_arrow_container = 2131099772;
			
			// aapt resource value: 0x7f060087
			public const int row_icon = 2131099783;
			
			// aapt resource value: 0x7f0600ad
			public const int row_important_link_description_TextView = 2131099821;
			
			// aapt resource value: 0x7f0600ab
			public const int row_important_link_goforword_ImageView = 2131099819;
			
			// aapt resource value: 0x7f0600ac
			public const int row_important_link_title_TextView = 2131099820;
			
			// aapt resource value: 0x7f060089
			public const int row_news_arrow = 2131099785;
			
			// aapt resource value: 0x7f0600eb
			public const int row_surveys_arrow = 2131099883;
			
			// aapt resource value: 0x7f060088
			public const int row_title = 2131099784;
			
			// aapt resource value: 0x7f0600c0
			public const int row_tracks_name_tv = 2131099840;
			
			// aapt resource value: 0x7f0600c1
			public const int sanfrancisco_bottom_tabs_container = 2131099841;
			
			// aapt resource value: 0x7f06013a
			public const int scheduleAddedImageView = 2131099962;
			
			// aapt resource value: 0x7f060034
			public const int scheduleImageView = 2131099700;
			
			// aapt resource value: 0x7f060184
			public const int schedule_tab_btn_container = 2131100036;
			
			// aapt resource value: 0x7f060185
			public const int schedule_tab_icon = 2131100037;
			
			// aapt resource value: 0x7f060103
			public const int searchTextView = 2131099907;
			
			// aapt resource value: 0x7f06007a
			public const int section = 2131099770;
			
			// aapt resource value: 0x7f06007b
			public const int sectionTitle = 2131099771;
			
			// aapt resource value: 0x7f0600db
			public const int select_filter_container = 2131099867;
			
			// aapt resource value: 0x7f0600dd
			public const int select_subtrack_filter_container = 2131099869;
			
			// aapt resource value: 0x7f060000
			public const int selected_view = 2131099648;
			
			// aapt resource value: 0x7f060029
			public const int selfiePreview_button_container = 2131099689;
			
			// aapt resource value: 0x7f06002a
			public const int selfiePreview_cancel_button = 2131099690;
			
			// aapt resource value: 0x7f06002d
			public const int selfiePreview_previewImageView = 2131099693;
			
			// aapt resource value: 0x7f06002c
			public const int selfiePreview_progressBar = 2131099692;
			
			// aapt resource value: 0x7f06002b
			public const int selfiePreview_save_button = 2131099691;
			
			// aapt resource value: 0x7f060133
			public const int seperator0 = 2131099955;
			
			// aapt resource value: 0x7f060199
			public const int seperator1 = 2131100057;
			
			// aapt resource value: 0x7f06017c
			public const int sessionDaysViewPager = 2131100028;
			
			// aapt resource value: 0x7f060135
			public const int sessionDescriptionTextView = 2131099957;
			
			// aapt resource value: 0x7f060182
			public const int sessionDetailListView = 2131100034;
			
			// aapt resource value: 0x7f06014f
			public const int sessionDetail_audience_container_id = 2131099983;
			
			// aapt resource value: 0x7f060150
			public const int sessionDetail_audience_container_value = 2131099984;
			
			// aapt resource value: 0x7f06014b
			public const int sessionDetail_compatancy_container = 2131099979;
			
			// aapt resource value: 0x7f060157
			public const int sessionDetail_industryTextView_value = 2131099991;
			
			// aapt resource value: 0x7f060156
			public const int sessionDetail_industry_id = 2131099990;
			
			// aapt resource value: 0x7f060148
			public const int sessionDetail_market_segment_container = 2131099976;
			
			// aapt resource value: 0x7f060147
			public const int sessionDetail_market_segment_id = 2131099975;
			
			// aapt resource value: 0x7f060149
			public const int sessionDetail_market_segment_value = 2131099977;
			
			// aapt resource value: 0x7f06014d
			public const int sessionDetail_product_n_topic_id = 2131099981;
			
			// aapt resource value: 0x7f06014e
			public const int sessionDetail_product_n_topic_value = 2131099982;
			
			// aapt resource value: 0x7f060155
			public const int sessionDetail_roleNameTextView_value = 2131099989;
			
			// aapt resource value: 0x7f060154
			public const int sessionDetail_role_container = 2131099988;
			
			// aapt resource value: 0x7f060153
			public const int sessionDetail_role_id = 2131099987;
			
			// aapt resource value: 0x7f060151
			public const int sessionDetail_session_type_id = 2131099985;
			
			// aapt resource value: 0x7f060152
			public const int sessionDetail_session_type_value = 2131099986;
			
			// aapt resource value: 0x7f060159
			public const int sessionDetail_skilllevel_container = 2131099993;
			
			// aapt resource value: 0x7f060158
			public const int sessionDetail_skilllevel_id = 2131099992;
			
			// aapt resource value: 0x7f060143
			public const int sessionDetail_subTrackSectionTextView_id = 2131099971;
			
			// aapt resource value: 0x7f060144
			public const int sessionDetail_subtrack_container_value = 2131099972;
			
			// aapt resource value: 0x7f060145
			public const int sessionDetail_technical_level_id = 2131099973;
			
			// aapt resource value: 0x7f060146
			public const int sessionDetail_technical_level_value = 2131099974;
			
			// aapt resource value: 0x7f06013d
			public const int sessionDetail_textview_id = 2131099965;
			
			// aapt resource value: 0x7f06013e
			public const int sessionDetail_textview_value = 2131099966;
			
			// aapt resource value: 0x7f060141
			public const int sessionDetail_trackTextView_id = 2131099969;
			
			// aapt resource value: 0x7f060142
			public const int sessionDetail_trackTextView_value = 2131099970;
			
			// aapt resource value: 0x7f0600ef
			public const int sessionDetail_tv_for_all = 2131099887;
			
			// aapt resource value: 0x7f06013f
			public const int sessionDetail_twitter_hash_tag_id = 2131099967;
			
			// aapt resource value: 0x7f060140
			public const int sessionDetail_twitter_hash_tag_value = 2131099968;
			
			// aapt resource value: 0x7f06015b
			public const int sessionDetails_speakerSectionTextView = 2131099995;
			
			// aapt resource value: 0x7f06012f
			public const int sessionDisplayNameTextView = 2131099951;
			
			// aapt resource value: 0x7f0600c6
			public const int sessionFragmentContainer = 2131099846;
			
			// aapt resource value: 0x7f0600da
			public const int sessionGroup = 2131099866;
			
			// aapt resource value: 0x7f06013c
			public const int sessionInfoContainer = 2131099964;
			
			// aapt resource value: 0x7f0600e0
			public const int sessionListView = 2131099872;
			
			// aapt resource value: 0x7f060132
			public const int sessionTimeTextView = 2131099954;
			
			// aapt resource value: 0x7f0600df
			public const int session_NoData_TextView = 2131099871;
			
			// aapt resource value: 0x7f06009e
			public const int session_address_tv = 2131099806;
			
			// aapt resource value: 0x7f060183
			public const int session_bottom_tabs_container = 2131100035;
			
			// aapt resource value: 0x7f06009f
			public const int session_date_time_tv = 2131099807;
			
			// aapt resource value: 0x7f06017a
			public const int session_day_search_edit_text = 2131100026;
			
			// aapt resource value: 0x7f060138
			public const int session_detail_add_to_schedule_tv_label = 2131099960;
			
			// aapt resource value: 0x7f06013b
			public const int session_detail_added_to_schedule_tv_label = 2131099963;
			
			// aapt resource value: 0x7f060134
			public const int session_detail_track_color = 2131099956;
			
			// aapt resource value: 0x7f060024
			public const int session_loading_container = 2131099684;
			
			// aapt resource value: 0x7f060163
			public const int session_reminder_container = 2131100003;
			
			// aapt resource value: 0x7f0600d5
			public const int session_search_btn = 2131099861;
			
			// aapt resource value: 0x7f0600d7
			public const int session_search_cancel_btn = 2131099863;
			
			// aapt resource value: 0x7f0600d6
			public const int session_search_cancel_container_btn = 2131099862;
			
			// aapt resource value: 0x7f0600d4
			public const int session_search_container = 2131099860;
			
			// aapt resource value: 0x7f0600d8
			public const int session_search_edit_text = 2131099864;
			
			// aapt resource value: 0x7f06009c
			public const int session_section_container = 2131099804;
			
			// aapt resource value: 0x7f06009b
			public const int session_star_image_btn = 2131099803;
			
			// aapt resource value: 0x7f06009d
			public const int session_title_name_tv = 2131099805;
			
			// aapt resource value: 0x7f0600a0
			public const int session_track_color = 2131099808;
			
			// aapt resource value: 0x7f060172
			public const int setting_icon = 2131100018;
			
			// aapt resource value: 0x7f060039
			public const int setting_menu_list = 2131099705;
			
			// aapt resource value: 0x7f0600be
			public const int settings_list_menu_textview = 2131099838;
			
			// aapt resource value: 0x7f0600bd
			public const int settings_row_parent = 2131099837;
			
			// aapt resource value: 0x7f0600b9
			public const int sf_image_dp = 2131099833;
			
			// aapt resource value: 0x7f0600ba
			public const int sf_image_external = 2131099834;
			
			// aapt resource value: 0x7f0600b7
			public const int sf_section = 2131099831;
			
			// aapt resource value: 0x7f0600b8
			public const int sf_sectionTitle = 2131099832;
			
			// aapt resource value: 0x7f0600bc
			public const int sf_text_desc = 2131099836;
			
			// aapt resource value: 0x7f0600bb
			public const int sf_text_title = 2131099835;
			
			// aapt resource value: 0x7f06008e
			public const int shareNewsActionButton = 2131099790;
			
			// aapt resource value: 0x7f060023
			public const int skipLoginTextView = 2131099683;
			
			// aapt resource value: 0x7f06017b
			public const int sliding_tabs = 2131100027;
			
			// aapt resource value: 0x7f0600e1
			public const int slidingmenumain = 2131099873;
			
			// aapt resource value: 0x7f060109
			public const int socialAllFeeds_action_container = 2131099913;
			
			// aapt resource value: 0x7f06010f
			public const int socialAllFeeds_action_more = 2131099919;
			
			// aapt resource value: 0x7f06010a
			public const int socialAllFeeds_content_container = 2131099914;
			
			// aapt resource value: 0x7f06010b
			public const int socialAllFeeds_description_textview = 2131099915;
			
			// aapt resource value: 0x7f06010d
			public const int socialAllFeeds_feed_image = 2131099917;
			
			// aapt resource value: 0x7f06010c
			public const int socialAllFeeds_feed_image_container = 2131099916;
			
			// aapt resource value: 0x7f060108
			public const int socialAllFeeds_handle_textview = 2131099912;
			
			// aapt resource value: 0x7f060113
			public const int socialAllFeeds_instagram_action_comment = 2131099923;
			
			// aapt resource value: 0x7f060111
			public const int socialAllFeeds_instagram_action_like = 2131099921;
			
			// aapt resource value: 0x7f06010e
			public const int socialAllFeeds_play_video_image = 2131099918;
			
			// aapt resource value: 0x7f060107
			public const int socialAllFeeds_social_icon_imageview = 2131099911;
			
			// aapt resource value: 0x7f060105
			public const int socialAllFeeds_time_textview = 2131099909;
			
			// aapt resource value: 0x7f060117
			public const int socialAllFeeds_twitter_action_favorite = 2131099927;
			
			// aapt resource value: 0x7f060116
			public const int socialAllFeeds_twitter_action_favorite_imageview = 2131099926;
			
			// aapt resource value: 0x7f060114
			public const int socialAllFeeds_twitter_action_reply = 2131099924;
			
			// aapt resource value: 0x7f060115
			public const int socialAllFeeds_twitter_action_retweet = 2131099925;
			
			// aapt resource value: 0x7f060104
			public const int socialAllFeeds_user_imageview = 2131099908;
			
			// aapt resource value: 0x7f060106
			public const int socialAllFeeds_user_name_textview = 2131099910;
			
			// aapt resource value: 0x7f060067
			public const int socialTwitterReply_camera_button = 2131099751;
			
			// aapt resource value: 0x7f060058
			public const int socialTwitterReply_cancel_button = 2131099736;
			
			// aapt resource value: 0x7f06005a
			public const int socialTwitterReply_char_count = 2131099738;
			
			// aapt resource value: 0x7f060068
			public const int socialTwitterReply_gallery_button = 2131099752;
			
			// aapt resource value: 0x7f060063
			public const int socialTwitterReply_image = 2131099747;
			
			// aapt resource value: 0x7f060062
			public const int socialTwitterReply_image_container = 2131099746;
			
			// aapt resource value: 0x7f060064
			public const int socialTwitterReply_reply = 2131099748;
			
			// aapt resource value: 0x7f060066
			public const int socialTwitterReply_selfie_button = 2131099750;
			
			// aapt resource value: 0x7f06005d
			public const int socialTwitterReply_sender_container = 2131099741;
			
			// aapt resource value: 0x7f060060
			public const int socialTwitterReply_sender_handle_textview = 2131099744;
			
			// aapt resource value: 0x7f06005e
			public const int socialTwitterReply_sender_imageview = 2131099742;
			
			// aapt resource value: 0x7f06005f
			public const int socialTwitterReply_sender_title_textview = 2131099743;
			
			// aapt resource value: 0x7f06005b
			public const int socialTwitterReply_tweet_button = 2131099739;
			
			// aapt resource value: 0x7f060061
			public const int socialTwitterReply_tweet_container = 2131099745;
			
			// aapt resource value: 0x7f060189
			public const int social_tabs_all_feed_button = 2131100041;
			
			// aapt resource value: 0x7f060188
			public const int social_tabs_container = 2131100040;
			
			// aapt resource value: 0x7f06018a
			public const int social_tabs_imp_link_button = 2131100042;
			
			// aapt resource value: 0x7f0600e2
			public const int speakerContainer = 2131099874;
			
			// aapt resource value: 0x7f06018e
			public const int speakerDetailLine = 2131100046;
			
			// aapt resource value: 0x7f0600e4
			public const int speakerInfoTextView = 2131099876;
			
			// aapt resource value: 0x7f0600ea
			public const int speakerListView = 2131099882;
			
			// aapt resource value: 0x7f0600e3
			public const int speakerNameTextView = 2131099875;
			
			// aapt resource value: 0x7f06018c
			public const int speaker_detail_company_name_tv = 2131100044;
			
			// aapt resource value: 0x7f06018f
			public const int speaker_detail_description_tv = 2131100047;
			
			// aapt resource value: 0x7f06018d
			public const int speaker_detail_desgination_tv = 2131100045;
			
			// aapt resource value: 0x7f060191
			public const int speaker_detail_listview = 2131100049;
			
			// aapt resource value: 0x7f06018b
			public const int speaker_detail_name_tv = 2131100043;
			
			// aapt resource value: 0x7f060190
			public const int speaker_detail_session_label = 2131100048;
			
			// aapt resource value: 0x7f0600e6
			public const int speaker_search_btn = 2131099878;
			
			// aapt resource value: 0x7f0600e8
			public const int speaker_search_cancel_btn = 2131099880;
			
			// aapt resource value: 0x7f0600e7
			public const int speaker_search_cancel_container_btn = 2131099879;
			
			// aapt resource value: 0x7f0600e5
			public const int speaker_search_container = 2131099877;
			
			// aapt resource value: 0x7f0600e9
			public const int speaker_search_edit_text = 2131099881;
			
			// aapt resource value: 0x7f06015a
			public const int speakercontainer = 2131099994;
			
			// aapt resource value: 0x7f060186
			public const int speakers_tab_btn_container = 2131100038;
			
			// aapt resource value: 0x7f060187
			public const int speakers_tab_icon = 2131100039;
			
			// aapt resource value: 0x7f06003f
			public const int splash_loadingText = 2131099711;
			
			// aapt resource value: 0x7f06003c
			public const int splash_loadingTextForPex = 2131099708;
			
			// aapt resource value: 0x7f06003e
			public const int splash_logo = 2131099710;
			
			// aapt resource value: 0x7f06003a
			public const int splash_main_container = 2131099706;
			
			// aapt resource value: 0x7f060193
			public const int sponsor_fragment_container = 2131100051;
			
			// aapt resource value: 0x7f06006a
			public const int sponsor_search_btn = 2131099754;
			
			// aapt resource value: 0x7f06006c
			public const int sponsor_search_cancel_btn = 2131099756;
			
			// aapt resource value: 0x7f06006b
			public const int sponsor_search_cancel_container_btn = 2131099755;
			
			// aapt resource value: 0x7f060069
			public const int sponsor_search_container = 2131099753;
			
			// aapt resource value: 0x7f06006d
			public const int sponsor_search_edit_text = 2131099757;
			
			// aapt resource value: 0x7f060197
			public const int sponsorsBoothTextView = 2131100055;
			
			// aapt resource value: 0x7f06019a
			public const int sponsorsDetailContainer = 2131100058;
			
			// aapt resource value: 0x7f060195
			public const int sponsorsDetailImageView = 2131100053;
			
			// aapt resource value: 0x7f06019b
			public const int sponsorsDetailTextView = 2131100059;
			
			// aapt resource value: 0x7f060198
			public const int sponsorsDetailWebSiteTextView = 2131100056;
			
			// aapt resource value: 0x7f06012b
			public const int sponsorsHorizontalScrollView = 2131099947;
			
			// aapt resource value: 0x7f06006f
			public const int sponsorsImageView = 2131099759;
			
			// aapt resource value: 0x7f060194
			public const int sponsorsNameTextView = 2131100052;
			
			// aapt resource value: 0x7f060070
			public const int sponsorsTextView = 2131099760;
			
			// aapt resource value: 0x7f060196
			public const int sponsorsTypeNameTextView = 2131100054;
			
			// aapt resource value: 0x7f06012a
			public const int sponsorslabelTextView = 2131099946;
			
			// aapt resource value: 0x7f060017
			public const int srollContainer = 2131099671;
			
			// aapt resource value: 0x7f060033
			public const int starUnstarImageView = 2131099699;
			
			// aapt resource value: 0x7f060057
			public const int surveyListView = 2131099735;
			
			// aapt resource value: 0x7f060045
			public const int surveyLoading = 2131099717;
			
			// aapt resource value: 0x7f06016d
			public const int surveyLoadingContainer = 2131100013;
			
			// aapt resource value: 0x7f06007e
			public const int surveyTitleTextView = 2131099774;
			
			// aapt resource value: 0x7f06016c
			public const int survey_NoData_TextView = 2131100012;
			
			// aapt resource value: 0x7f060056
			public const int survey_header_text_view = 2131099734;
			
			// aapt resource value: 0x7f0600ed
			public const int surveys_session_title = 2131099885;
			
			// aapt resource value: 0x7f0600ec
			public const int surveys_textview_title = 2131099884;
			
			// aapt resource value: 0x7f060171
			public const int sync_icon = 2131100017;
			
			// aapt resource value: 0x7f06016b
			public const int sync_info_textview = 2131100011;
			
			// aapt resource value: 0x7f0600cd
			public const int tagContainers = 2131099853;
			
			// aapt resource value: 0x7f0600d3
			public const int tagMainContainer = 2131099859;
			
			// aapt resource value: 0x7f0600cb
			public const int tagSuggestContainers = 2131099851;
			
			// aapt resource value: 0x7f06017f
			public const int tag_close_imageview = 2131100031;
			
			// aapt resource value: 0x7f0600ce
			public const int tag_edit_text = 2131099854;
			
			// aapt resource value: 0x7f0600cc
			public const int tagsHorizontalScrollView = 2131099852;
			
			// aapt resource value: 0x7f060035
			public const int tagsImageView = 2131099701;
			
			// aapt resource value: 0x7f0600ca
			public const int tagsSuggestionHorizontalScrollView = 2131099850;
			
			// aapt resource value: 0x7f060118
			public const int takeSelfieTextView = 2131099928;
			
			// aapt resource value: 0x7f060167
			public const int take_photo_container = 2131100007;
			
			// aapt resource value: 0x7f060168
			public const int take_photo_icon = 2131100008;
			
			// aapt resource value: 0x7f060169
			public const int take_photo_label = 2131100009;
			
			// aapt resource value: 0x7f06001f
			public const int termsAndConditionTextView = 2131099679;
			
			// aapt resource value: 0x7f060047
			public const int title = 2131099719;
			
			// aapt resource value: 0x7f0600fe
			public const int titleTextView = 2131099902;
			
			// aapt resource value: 0x7f0600bf
			public const int togglePushNotification = 2131099839;
			
			// aapt resource value: 0x7f06011c
			public const int topContainer = 2131099932;
			
			// aapt resource value: 0x7f060162
			public const int top_left_drawer_title_container = 2131100002;
			
			// aapt resource value: 0x7f06019c
			public const int track_line1 = 2131100060;
			
			// aapt resource value: 0x7f06019f
			public const int track_line2 = 2131100063;
			
			// aapt resource value: 0x7f06012d
			public const int tracksHorizontalScrollView = 2131099949;
			
			// aapt resource value: 0x7f06012c
			public const int trackslabelTextView = 2131099948;
			
			// aapt resource value: 0x7f0600ee
			public const int transportationListView = 2131099886;
			
			// aapt resource value: 0x7f060073
			public const int tvDate = 2131099763;
			
			// aapt resource value: 0x7f060036
			public const int twitterImageView = 2131099702;
			
			// aapt resource value: 0x7f060042
			public const int twitterLoginWebView = 2131099714;
			
			// aapt resource value: 0x7f060059
			public const int twitterText = 2131099737;
			
			// aapt resource value: 0x7f06001c
			public const int userNameEditText = 2131099676;
			
			// aapt resource value: 0x7f060170
			public const int user_container = 2131100016;
			
			// aapt resource value: 0x7f060177
			public const int user_displayname = 2131100023;
			
			// aapt resource value: 0x7f060176
			public const int user_dp = 2131100022;
			
			// aapt resource value: 0x7f060161
			public const int view_left_drawer = 2131100001;
			
			// aapt resource value: 0x7f060041
			public const int webView = 2131099713;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Integer
		{
			
			// aapt resource value: 0x7f090000
			public const int num_cols = 2131296256;
			
			static Integer()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Integer()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int activity_hands_on_labs_detail = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int activity_image_preview = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int activity_login = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int activity_moscone_center = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int activity_selfie_image_preview = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int activity_session_detail_screen = 2130903045;
			
			// aapt resource value: 0x7f030006
			public const int activity_settings = 2130903046;
			
			// aapt resource value: 0x7f030007
			public const int activity_speaker_details = 2130903047;
			
			// aapt resource value: 0x7f030008
			public const int activity_splash_screen = 2130903048;
			
			// aapt resource value: 0x7f030009
			public const int activity_terms_and_condition = 2130903049;
			
			// aapt resource value: 0x7f03000a
			public const int activity_twitter_login = 2130903050;
			
			// aapt resource value: 0x7f03000b
			public const int activity_uihands_on_labs = 2130903051;
			
			// aapt resource value: 0x7f03000c
			public const int activity_web_view = 2130903052;
			
			// aapt resource value: 0x7f03000d
			public const int activity_web_view_for_survey = 2130903053;
			
			// aapt resource value: 0x7f03000e
			public const int agenda_row = 2130903054;
			
			// aapt resource value: 0x7f03000f
			public const int allFeedsLayout = 2130903055;
			
			// aapt resource value: 0x7f030010
			public const int DailyHighlightsLayout = 2130903056;
			
			// aapt resource value: 0x7f030011
			public const int faq_list_item = 2130903057;
			
			// aapt resource value: 0x7f030012
			public const int faq_row = 2130903058;
			
			// aapt resource value: 0x7f030013
			public const int FoodNDrinkLayout = 2130903059;
			
			// aapt resource value: 0x7f030014
			public const int fragment_explore = 2130903060;
			
			// aapt resource value: 0x7f030015
			public const int fragment_important_link = 2130903061;
			
			// aapt resource value: 0x7f030016
			public const int fragment_my_notes = 2130903062;
			
			// aapt resource value: 0x7f030017
			public const int fragment_my_survey_completed = 2130903063;
			
			// aapt resource value: 0x7f030018
			public const int fragment_social_tweet_dialog_fragment = 2130903064;
			
			// aapt resource value: 0x7f030019
			public const int fragment_sponsors_by_contributors = 2130903065;
			
			// aapt resource value: 0x7f03001a
			public const int grid_row_sponsors_by_contribution = 2130903066;
			
			// aapt resource value: 0x7f03001b
			public const int header_agenda = 2130903067;
			
			// aapt resource value: 0x7f03001c
			public const int header_menu = 2130903068;
			
			// aapt resource value: 0x7f03001d
			public const int horizontal_list = 2130903069;
			
			// aapt resource value: 0x7f03001e
			public const int list = 2130903070;
			
			// aapt resource value: 0x7f03001f
			public const int list_header = 2130903071;
			
			// aapt resource value: 0x7f030020
			public const int list_item = 2130903072;
			
			// aapt resource value: 0x7f030021
			public const int list_row_hands_on_labs = 2130903073;
			
			// aapt resource value: 0x7f030022
			public const int list_row_notes = 2130903074;
			
			// aapt resource value: 0x7f030023
			public const int loading_gamification = 2130903075;
			
			// aapt resource value: 0x7f030024
			public const int Main = 2130903076;
			
			// aapt resource value: 0x7f030025
			public const int menu_frame = 2130903077;
			
			// aapt resource value: 0x7f030026
			public const int menu_list = 2130903078;
			
			// aapt resource value: 0x7f030027
			public const int menu_row = 2130903079;
			
			// aapt resource value: 0x7f030028
			public const int NewsCells = 2130903080;
			
			// aapt resource value: 0x7f030029
			public const int NewsDetails = 2130903081;
			
			// aapt resource value: 0x7f03002a
			public const int prog_faq = 2130903082;
			
			// aapt resource value: 0x7f03002b
			public const int pull_to_refresh_header = 2130903083;
			
			// aapt resource value: 0x7f03002c
			public const int pulltorefreshlist = 2130903084;
			
			// aapt resource value: 0x7f03002d
			public const int row_all_session = 2130903085;
			
			// aapt resource value: 0x7f03002e
			public const int row_explore_top_now_design = 2130903086;
			
			// aapt resource value: 0x7f03002f
			public const int row_important_link = 2130903087;
			
			// aapt resource value: 0x7f030030
			public const int row_left_drawer = 2130903088;
			
			// aapt resource value: 0x7f030031
			public const int row_list_sf = 2130903089;
			
			// aapt resource value: 0x7f030032
			public const int row_settings_list = 2130903090;
			
			// aapt resource value: 0x7f030033
			public const int row_tracks_session = 2130903091;
			
			// aapt resource value: 0x7f030034
			public const int sanfrancisco = 2130903092;
			
			// aapt resource value: 0x7f030035
			public const int scheduleAndInterest = 2130903093;
			
			// aapt resource value: 0x7f030036
			public const int screen_note_detail = 2130903094;
			
			// aapt resource value: 0x7f030037
			public const int session_row = 2130903095;
			
			// aapt resource value: 0x7f030038
			public const int sessionLayout = 2130903096;
			
			// aapt resource value: 0x7f030039
			public const int slidingmenumain = 2130903097;
			
			// aapt resource value: 0x7f03003a
			public const int speaker_row = 2130903098;
			
			// aapt resource value: 0x7f03003b
			public const int speakerLayout = 2130903099;
			
			// aapt resource value: 0x7f03003c
			public const int survey_row = 2130903100;
			
			// aapt resource value: 0x7f03003d
			public const int temp = 2130903101;
			
			// aapt resource value: 0x7f03003e
			public const int transportationLayout = 2130903102;
			
			// aapt resource value: 0x7f03003f
			public const int tv_session_deails_value = 2130903103;
			
			// aapt resource value: 0x7f030040
			public const int VenueCells = 2130903104;
			
			// aapt resource value: 0x7f030041
			public const int VenueLayout = 2130903105;
			
			// aapt resource value: 0x7f030042
			public const int view_actionbar = 2130903106;
			
			// aapt resource value: 0x7f030043
			public const int view_all_feeds = 2130903107;
			
			// aapt resource value: 0x7f030044
			public const int view_bottom_instagram_actions = 2130903108;
			
			// aapt resource value: 0x7f030045
			public const int view_bottom_twitter_actions = 2130903109;
			
			// aapt resource value: 0x7f030046
			public const int view_bottom_twitter_post_action = 2130903110;
			
			// aapt resource value: 0x7f030047
			public const int view_hands_on_labs_fragment = 2130903111;
			
			// aapt resource value: 0x7f030048
			public const int view_header_explore_screen = 2130903112;
			
			// aapt resource value: 0x7f030049
			public const int view_header_session_detail_screen = 2130903113;
			
			// aapt resource value: 0x7f03004a
			public const int view_horizontal_scroll_view = 2130903114;
			
			// aapt resource value: 0x7f03004b
			public const int view_image_adapter = 2130903115;
			
			// aapt resource value: 0x7f03004c
			public const int view_left_drawer = 2130903116;
			
			// aapt resource value: 0x7f03004d
			public const int view_left_menu_sync_info = 2130903117;
			
			// aapt resource value: 0x7f03004e
			public const int view_list = 2130903118;
			
			// aapt resource value: 0x7f03004f
			public const int view_loading = 2130903119;
			
			// aapt resource value: 0x7f030050
			public const int view_loading_list = 2130903120;
			
			// aapt resource value: 0x7f030051
			public const int view_login_continer_left_side_menu = 2130903121;
			
			// aapt resource value: 0x7f030052
			public const int view_my_interest = 2130903122;
			
			// aapt resource value: 0x7f030053
			public const int view_my_schedule = 2130903123;
			
			// aapt resource value: 0x7f030054
			public const int view_schedule = 2130903124;
			
			// aapt resource value: 0x7f030055
			public const int view_selection_button = 2130903125;
			
			// aapt resource value: 0x7f030056
			public const int view_session_day_top_header = 2130903126;
			
			// aapt resource value: 0x7f030057
			public const int view_session_detail_pager_adapter = 2130903127;
			
			// aapt resource value: 0x7f030058
			public const int view_sessions = 2130903128;
			
			// aapt resource value: 0x7f030059
			public const int view_social = 2130903129;
			
			// aapt resource value: 0x7f03005a
			public const int view_speaker_detail_header = 2130903130;
			
			// aapt resource value: 0x7f03005b
			public const int view_speakers_detail_pager_adapter = 2130903131;
			
			// aapt resource value: 0x7f03005c
			public const int view_sponsor_contribution_header = 2130903132;
			
			// aapt resource value: 0x7f03005d
			public const int view_sponsors = 2130903133;
			
			// aapt resource value: 0x7f03005e
			public const int view_sponsors_detail_pager_adapter = 2130903134;
			
			// aapt resource value: 0x7f03005f
			public const int view_tracks_filter_dialog = 2130903135;
			
			// aapt resource value: 0x7f030060
			public const int view_twitter_reply_alert_box = 2130903136;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			// aapt resource value: 0x7f050043
			public const int add_note_text = 2131034179;
			
			// aapt resource value: 0x7f05003f
			public const int add_photo_text = 2131034175;
			
			// aapt resource value: 0x7f05001a
			public const int add_to_my_schedule = 2131034138;
			
			// aapt resource value: 0x7f050019
			public const int added_to_schedule = 2131034137;
			
			// aapt resource value: 0x7f050018
			public const int advanced_text = 2131034136;
			
			// aapt resource value: 0x7f050026
			public const int allfeeds_camel_case = 2131034150;
			
			// aapt resource value: 0x7f050037
			public const int app_name = 2131034167;
			
			// aapt resource value: 0x7f050061
			public const int authenticating_your_app_message = 2131034209;
			
			// aapt resource value: 0x7f050017
			public const int beginner_text = 2131034135;
			
			// aapt resource value: 0x7f050040
			public const int booth_text = 2131034176;
			
			// aapt resource value: 0x7f050004
			public const int cancel_text = 2131034116;
			
			// aapt resource value: 0x7f05006a
			public const int cannot_retweet_status_text = 2131034218;
			
			// aapt resource value: 0x7f050021
			public const int capacity = 2131034145;
			
			// aapt resource value: 0x7f050056
			public const int checking_for_updates_sync_text = 2131034198;
			
			// aapt resource value: 0x7f05001e
			public const int clear_filter_text = 2131034142;
			
			// aapt resource value: 0x7f05003b
			public const int description_text = 2131034171;
			
			// aapt resource value: 0x7f05001b
			public const int done_text = 2131034139;
			
			// aapt resource value: 0x7f05002c
			public const int dp = 2131034156;
			
			// aapt resource value: 0x7f050020
			public const int duration = 2131034144;
			
			// aapt resource value: 0x7f050065
			public const int email_text = 2131034213;
			
			// aapt resource value: 0x7f05004e
			public const int fa_bars = 2131034190;
			
			// aapt resource value: 0x7f050054
			public const int fa_bell_o = 2131034196;
			
			// aapt resource value: 0x7f050053
			public const int fa_camera = 2131034195;
			
			// aapt resource value: 0x7f050052
			public const int fa_edit = 2131034194;
			
			// aapt resource value: 0x7f050051
			public const int fa_gear = 2131034193;
			
			// aapt resource value: 0x7f050050
			public const int fa_refresh = 2131034192;
			
			// aapt resource value: 0x7f050055
			public const int fa_search = 2131034197;
			
			// aapt resource value: 0x7f05004f
			public const int fa_twitter = 2131034191;
			
			// aapt resource value: 0x7f05006d
			public const int fail_text = 2131034221;
			
			// aapt resource value: 0x7f050064
			public const int favorite_text = 2131034212;
			
			// aapt resource value: 0x7f05002e
			public const int forgot_password_text = 2131034158;
			
			// aapt resource value: 0x7f05002f
			public const int forgot_useraname_text = 2131034159;
			
			// aapt resource value: 0x7f050030
			public const int important_link = 2131034160;
			
			// aapt resource value: 0x7f050015
			public const int industry_name_text = 2131034133;
			
			// aapt resource value: 0x7f05003e
			public const int last_edited_text = 2131034174;
			
			// aapt resource value: 0x7f050058
			public const int last_updated_sync_text = 2131034200;
			
			// aapt resource value: 0x7f050025
			public const int leaderboard_capital_text = 2131034149;
			
			// aapt resource value: 0x7f050022
			public const int loading_text = 2131034146;
			
			// aapt resource value: 0x7f050033
			public const int login_screen_text = 2131034163;
			
			// aapt resource value: 0x7f05002b
			public const int login_text = 2131034155;
			
			// aapt resource value: 0x7f050066
			public const int message_text = 2131034214;
			
			// aapt resource value: 0x7f050016
			public const int my_survey_single = 2131034134;
			
			// aapt resource value: 0x7f050070
			public const int network_issue_text = 2131034224;
			
			// aapt resource value: 0x7f050024
			public const int next_up = 2131034148;
			
			// aapt resource value: 0x7f050046
			public const int no_image = 2131034182;
			
			// aapt resource value: 0x7f050008
			public const int no_internet_connection_text = 2131034120;
			
			// aapt resource value: 0x7f05006e
			public const int no_network_text = 2131034222;
			
			// aapt resource value: 0x7f05005b
			public const int no_new_updates_sync_text = 2131034203;
			
			// aapt resource value: 0x7f050039
			public const int no_survey_text = 2131034169;
			
			// aapt resource value: 0x7f050068
			public const int no_text = 2131034216;
			
			// aapt resource value: 0x7f050023
			public const int on_now = 2131034147;
			
			// aapt resource value: 0x7f05005f
			public const int oops_something_went_wrong = 2131034207;
			
			// aapt resource value: 0x7f05002d
			public const int password_text = 2131034157;
			
			// aapt resource value: 0x7f050036
			public const int please_enter_password_text = 2131034166;
			
			// aapt resource value: 0x7f050035
			public const int please_enter_username_text = 2131034165;
			
			// aapt resource value: 0x7f05001d
			public const int please_wait = 2131034141;
			
			// aapt resource value: 0x7f050031
			public const int please_wait_text = 2131034161;
			
			// aapt resource value: 0x7f050060
			public const int please_wait_title = 2131034208;
			
			// aapt resource value: 0x7f050047
			public const int pull_to_refresh_pull_label = 2131034183;
			
			// aapt resource value: 0x7f050049
			public const int pull_to_refresh_refreshing_label = 2131034185;
			
			// aapt resource value: 0x7f050048
			public const int pull_to_refresh_release_label = 2131034184;
			
			// aapt resource value: 0x7f05004a
			public const int pull_to_refresh_tap_label = 2131034186;
			
			// aapt resource value: 0x7f050041
			public const int qr_codes_text = 2131034177;
			
			// aapt resource value: 0x7f050027
			public const int recommended_session_capital_text = 2131034151;
			
			// aapt resource value: 0x7f050071
			public const int reply_mention_text = 2131034225;
			
			// aapt resource value: 0x7f050062
			public const int reply_text = 2131034210;
			
			// aapt resource value: 0x7f050072
			public const int reply_text_can_not_be_blank_text = 2131034226;
			
			// aapt resource value: 0x7f050067
			public const int retweet_text = 2131034215;
			
			// aapt resource value: 0x7f050069
			public const int retweet_this_to_your_followers_text = 2131034217;
			
			// aapt resource value: 0x7f050014
			public const int role_camel_case = 2131034132;
			
			// aapt resource value: 0x7f05003d
			public const int save_text = 2131034173;
			
			// aapt resource value: 0x7f050003
			public const int search_text = 2131034115;
			
			// aapt resource value: 0x7f050012
			public const int session_detail_audience = 2131034130;
			
			// aapt resource value: 0x7f050011
			public const int session_detail_competency = 2131034129;
			
			// aapt resource value: 0x7f050010
			public const int session_detail_id = 2131034128;
			
			// aapt resource value: 0x7f05000f
			public const int session_detail_market_segment = 2131034127;
			
			// aapt resource value: 0x7f05000e
			public const int session_detail_product_n_topic = 2131034126;
			
			// aapt resource value: 0x7f05000d
			public const int session_detail_session_type = 2131034125;
			
			// aapt resource value: 0x7f05000c
			public const int session_detail_technical_level = 2131034124;
			
			// aapt resource value: 0x7f05000b
			public const int session_detail_twitter_hashtag = 2131034123;
			
			// aapt resource value: 0x7f05001c
			public const int session_text = 2131034140;
			
			// aapt resource value: 0x7f05001f
			public const int sessions_text = 2131034143;
			
			// aapt resource value: 0x7f050002
			public const int settings_text = 2131034114;
			
			// aapt resource value: 0x7f05000a
			public const int skill_level_camel_case = 2131034122;
			
			// aapt resource value: 0x7f05004c
			public const int social_all_feeds_camera_text = 2131034188;
			
			// aapt resource value: 0x7f05004d
			public const int social_all_feeds_new_tweet_text = 2131034189;
			
			// aapt resource value: 0x7f05004b
			public const int social_all_feeds_take_selfie_text = 2131034187;
			
			// aapt resource value: 0x7f05006b
			public const int social_post_options_text = 2131034219;
			
			// aapt resource value: 0x7f050044
			public const int social_post_text = 2131034180;
			
			// aapt resource value: 0x7f050009
			public const int speaker_capital_name_text = 2131034121;
			
			// aapt resource value: 0x7f050013
			public const int speaker_text = 2131034131;
			
			// aapt resource value: 0x7f050028
			public const int sponsors_capital_text = 2131034152;
			
			// aapt resource value: 0x7f050006
			public const int sub_track_text = 2131034118;
			
			// aapt resource value: 0x7f050007
			public const int sub_tracks_text = 2131034119;
			
			// aapt resource value: 0x7f05006c
			public const int success_text = 2131034220;
			
			// aapt resource value: 0x7f05003a
			public const int tag_text = 2131034170;
			
			// aapt resource value: 0x7f05002a
			public const int take_photo_text = 2131034154;
			
			// aapt resource value: 0x7f050034
			public const int terms_and_conditions_small_text = 2131034164;
			
			// aapt resource value: 0x7f05003c
			public const int title_text = 2131034172;
			
			// aapt resource value: 0x7f05005d
			public const int today_at_sync_text = 2131034205;
			
			// aapt resource value: 0x7f050005
			public const int track_name_text = 2131034117;
			
			// aapt resource value: 0x7f050029
			public const int tracks_capital_text = 2131034153;
			
			// aapt resource value: 0x7f05006f
			public const int tweet_can_not_be_blank_text = 2131034223;
			
			// aapt resource value: 0x7f050045
			public const int twitter_camel_case = 2131034181;
			
			// aapt resource value: 0x7f05005e
			public const int twitter_login_text = 2131034206;
			
			// aapt resource value: 0x7f050059
			public const int updates_available_sync_text = 2131034201;
			
			// aapt resource value: 0x7f05005a
			public const int updating_sync_text = 2131034202;
			
			// aapt resource value: 0x7f050032
			public const int username_text = 2131034162;
			
			// aapt resource value: 0x7f050042
			public const int visit_sponsor_text = 2131034178;
			
			// aapt resource value: 0x7f050038
			public const int vmworld2014_text = 2131034168;
			
			// aapt resource value: 0x7f050063
			public const int yes_text = 2131034211;
			
			// aapt resource value: 0x7f05005c
			public const int yesterday_at_sync_text = 2131034204;
			
			// aapt resource value: 0x7f050057
			public const int your_data_is_up_to_date_sync_text = 2131034199;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f0a0000
			public const int DefaultTheme = 2131361792;
			
			// aapt resource value: 0x7f0a0001
			public const int DialogAnimation = 2131361793;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] SlidingMenu = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973,
					2130771974,
					2130771975,
					2130771976,
					2130771977,
					2130771978,
					2130771979,
					2130771980,
					2130771981};
			
			// aapt resource value: 3
			public const int SlidingMenu_behindOffset = 3;
			
			// aapt resource value: 5
			public const int SlidingMenu_behindScrollScale = 5;
			
			// aapt resource value: 4
			public const int SlidingMenu_behindWidth = 4;
			
			// aapt resource value: 11
			public const int SlidingMenu_fadeDegree = 11;
			
			// aapt resource value: 10
			public const int SlidingMenu_fadeEnabled = 10;
			
			// aapt resource value: 0
			public const int SlidingMenu_mode = 0;
			
			// aapt resource value: 13
			public const int SlidingMenu_selectorDrawable = 13;
			
			// aapt resource value: 12
			public const int SlidingMenu_selectorEnabled = 12;
			
			// aapt resource value: 8
			public const int SlidingMenu_shadowDrawable = 8;
			
			// aapt resource value: 9
			public const int SlidingMenu_shadowWidth = 9;
			
			// aapt resource value: 6
			public const int SlidingMenu_touchModeAbove = 6;
			
			// aapt resource value: 7
			public const int SlidingMenu_touchModeBehind = 7;
			
			// aapt resource value: 1
			public const int SlidingMenu_viewAbove = 1;
			
			// aapt resource value: 2
			public const int SlidingMenu_viewBehind = 2;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
